### PR TITLE
Add support for letter spacing to typeset mixin

### PR DESCRIPTION
**Pull request by rikki-iki**

### CODE REVIEW

**Comment by rootwork** [comment]
+1 on this. Letter-spacing is so closely tied to typography, it's sometimes frustrating to not be able to bundle it into a typeset.

**Comment by jptaranto** [comment]
I'll have to spend a little more time on this one as it will mess with the typeset shorthand. The intended functionality was originally to bundle letter-spacing with typefaces but your all right, it would be better to bundle it with typesets as it's often dependent on font size.

**Comment by rootwork** [comment]
While you're at it, it would be nice to also include `font-style` in there. I always forget that I can set weight in typesets, but not italics.

**Comment by jptaranto** [comment]
Closing this now as it's been implemented in 1.1.x alpha.

**Pull request closed without merging**
